### ISSUE TITLE
Flyway migrate failing - JDBC - placeholders

### ISSUE THREAD

**Issue by rafaelqntn-cfi** [flyway/flyway-community-db-support#64]
## Description
The migration command fails when a placeholder for replacement is passed.

The JDBC driver causes a flyway failure when preparing the statement to retrieve the current schema (`SELECT current_schema()`) at `org.flywaydb.core.internal.jdbc.JdbcTemplate.prepareStatement(JdbcTemplate.java:313)`. The error message mentions that a "Configuration" matching the placeholder key "is not available" (verbatim: "Configuration **key1** is not available."). See Scenario 2 output.

## Details

Flyway --version output
```
Flyway OSS Edition 10.20.1 by Redgate

See release notes here: https://rd.gt/416ObMi
Plugin Name     | Version  
--------------- | ---------
DB2 for z/OS    | 10.16.3
OceanBase       | 10.16.0
TiDB            | 10.16.0
YugabyteDB      | 10.16.0
ClickHouse      | 10.16.0
Apache Ignite   | 10.16.0
```

JDBC Info: `Driver: DatabricksJDBC 02.06.38.1068`

Config file: flyway.toml
```
[flyway]
defaultSchema = "flyway_test"

[environments.dev]
url = "jdbc:databricks://[REDACTED];ConnCatalog=dev;httpPath=[REDACTED];UseNativeQuery=1;transportMode=http;ssl=1;EnableArrow=0;AuthMech=3;UID=token;PWD=[REDACTED]"
```

## Scenario 1
- No placeholders in the command
- No placeholders in SQL file

### Command:
```
flyway migrate -environment=dev -configFiles=.\sql\migrations\conf\flyway.toml -locations=filesystem:./sql/migrations -n -X
```

### Migration file:
R__repeatable.sql
```
select 'placeholder value';
```

### Output:
```
[...]
DEBUG: Starting migration of schema `flyway_test` with repeatable migration "repeatable" ...
Migrating schema `flyway_test` with repeatable migration "repeatable"
DEBUG: Executing SQL: select 'placeholder value'
+------------------+
| placeholder value |
+------------------+
| placeholder value |
+------------------+

DEBUG: Successfully completed migration of schema `flyway_test` with repeatable migration "repeatable"
DEBUG: Schema History table `flyway_test`.`flyway_schema_history` successfully updated to reflect changes
DEBUG: Performing operation in non-transactional context.
DEBUG: Updating lock in Flyway schema history table
DEBUG: CherryPickConfigurationExtension not found
Successfully applied 1 migration to schema `flyway_test` (execution time 00:00.668s)
DEBUG: Performing operation in non-transactional context.
DEBUG: Memory usage: 46 of 120M
```

## Scenario 2
- Placeholders in the command
- Placeholders in SQL file

### Command:
```
flyway migrate -environment=dev -placeholders.key1=value -configFiles=.\sql\migrations\conf\flyway.toml -locations=filesystem:./sql/migrations -n -X
```

### Migration file:
R__repeatable.sql
```
select 'placeholder ${key1}';
```

### Output:
```
[...]
DEBUG: Using configuration:
[...]
flyway.placeholders -> {key1=value}
[...]
ERROR: Unexpected error
org.flywaydb.core.internal.exception.FlywaySqlException: Unable to determine the original schema for the connection
----------------------------------------------------------
SQL State  : HY000
Error Code : 500051
Message    : [Databricks][JDBCDriver](500051) ERROR processing query/statement. Error Code: 0, SQL state: null, Query: SELECT current_schema(), Error message from Server: Configuration key1 is not available..
    [...]
Caused by: java.sql.SQLException: [Databricks][JDBCDriver](500051) ERROR processing query/statement. Error Code: 0, SQL state: null, Query: SELECT current_schema(), Error message from Server: Configuration key1 is not available..
    [...]
Caused by: com.databricks.client.support.exceptions.GeneralException: [Databricks][JDBCDriver](500051) ERROR processing query/statement. Error Code: 0, SQL state: null, Query: SELECT current_schema(), Error message from Server: Configuration key1 is not available..
	... 35 more
```

## Scenario 3
- No placeholders in the command
- Placeholders in SQL file

### Command:
```
flyway migrate -environment=dev -configFiles=.\sql\migrations\conf\flyway.toml -locations=filesystem:./sql/migrations -n -X
```

### Migration file:
R__repeatable.sql
```
select 'placeholder ${key1}';
```

### Output:
```
ERROR: Unexpected error
org.flywaydb.core.api.FlywayException: No value provided for placeholder: ${key1}.  Check your configuration!
    [...]
	at org.flywaydb.commandline.Main.main(Main.java:127)
```

**Comment by JasonLuo-Redgate** [comment]
Hi @rafaelqntn-cfi ,
For `Scenario 2`, besides putting `key1` in R__repeatable.sql, have you configured `key1` anywhere else? 
Because if it's only inside a `select` sql statement, it could hardly impact `JDBCDriver`.

**Comment by rafaelqntn-cfi** [comment]
Hi, @JasonLuo-Redgate. Thanks for looking into this issue.
Yes, I configured. Please refer to the Scenario 2 **Command** section, where I added the parameter `-placeholders.key1=value`, which generates the debug output `flyway.placeholders -> {key1=value}` meaning that Flyway has the placeholder in memory.

I also tried to put the placeholder in the config file with the same outcome, so for easier reproducibility, I kept the simplest possible config file and changed the commands and `R__` SQL scripts for the scenarios.

I summarized the important points of the debug outputs, but part of the problem happened in the "proprietary" part of their JDBC code (`Unknown Source`), where I could not step through the code properly. Please check the full stack trace I pasted below, what happens after the `org.flywaydb.core.internal.jdbc.JdbcTemplate.prepareStatement(JdbcTemplate.java:313)` line:
```
org.flywaydb.core.internal.exception.FlywaySqlException: Unable to determine the original schema for the connection
----------------------------------------------------------
SQL State  : HY000
Error Code : 500051
Message    : [Databricks][JDBCDriver](500051) ERROR processing query/statement. Error Code: 0, SQL state: null, Query: SELECT current_schema(), Error message from Server: Configuration key1 is not available..

	at org.flywaydb.core.internal.database.base.Connection.<init>(Connection.java:55)
	at org.flywaydb.community.database.databricks.DatabricksConnection.<init>(DatabricksConnection.java:31)
	at org.flywaydb.community.database.databricks.DatabricksDatabase.doGetConnection(DatabricksDatabase.java:39)
	at org.flywaydb.community.database.databricks.DatabricksDatabase.doGetConnection(DatabricksDatabase.java:32)
	at org.flywaydb.core.internal.database.base.Database.getConnection(Database.java:104)
	at org.flywaydb.core.internal.database.base.Database.getMainConnection(Database.java:295)
	at org.flywaydb.core.internal.schemahistory.SchemaHistoryFactory.prepareSchemas(SchemaHistoryFactory.java:77)
	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:189)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:176)
	at org.flywaydb.commandline.Main.executeOperation(Main.java:298)
	at org.flywaydb.commandline.Main.executeFlyway(Main.java:204)
	at org.flywaydb.commandline.Main.main(Main.java:127)
Caused by: java.sql.SQLException: [Databricks][JDBCDriver](500051) ERROR processing query/statement. Error Code: 0, SQL state: null, Query: SELECT current_schema(), Error message from Server: Configuration key1 is not available..
	at com.databricks.client.hivecommon.api.HS2Client.buildExceptionFromTStatusSqlState(Unknown Source)
	at com.databricks.client.hivecommon.api.HS2Client.buildExceptionFromTStatus(Unknown Source)
	at com.databricks.client.hivecommon.api.HS2Client.checkResponseStatus(Unknown Source)
	at com.databricks.client.hivecommon.api.HS2Client.executeStatementInternal(Unknown Source)
	at com.databricks.client.hivecommon.api.HS2Client.executeStatement(Unknown Source)
	at com.databricks.client.hivecommon.dataengine.HiveJDBCNativeQueryExecutor.executeNonRowCountQueryHelper(Unknown Source)
	at com.databricks.client.hivecommon.dataengine.HiveJDBCNativeQueryExecutor.executeQuery(Unknown Source)
	at com.databricks.client.hivecommon.dataengine.HiveJDBCNativeQueryExecutor.<init>(Unknown Source)
	at com.databricks.client.hivecommon.dataengine.HiveJDBCDataEngine.prepare(Unknown Source)
	at com.databricks.client.jdbc.common.SPreparedStatement.<init>(Unknown Source)
	at com.databricks.client.jdbc.jdbc41.S41PreparedStatement.<init>(Unknown Source)
	at com.databricks.client.jdbc.jdbc42.S42PreparedStatement.<init>(Unknown Source)
	at com.databricks.client.hivecommon.jdbc42.Hive42PreparedStatement.<init>(Unknown Source)
	at com.databricks.client.spark.jdbc.SparkJDBCObjectFactory.createPreparedStatement(Unknown Source)
	at com.databricks.client.jdbc.common.JDBCObjectFactory.newPreparedStatement(Unknown Source)
	at com.databricks.client.jdbc.common.SConnection$5.create(Unknown Source)
	at com.databricks.client.jdbc.common.SConnection$5.create(Unknown Source)
	at com.databricks.client.jdbc.common.SConnection$StatementCreator.create(Unknown Source)
	at com.databricks.client.jdbc.common.SConnection.prepareStatement(Unknown Source)
	at com.databricks.client.jdbc.common.SConnection.prepareStatement(Unknown Source)
	at com.databricks.client.jdbc.common.SConnection.prepareStatement(Unknown Source)
	at org.flywaydb.core.internal.jdbc.JdbcTemplate.prepareStatement(JdbcTemplate.java:313)
	at org.flywaydb.core.internal.jdbc.JdbcTemplate.queryForString(JdbcTemplate.java:164)
	at org.flywaydb.community.database.databricks.DatabricksConnection.getCurrentSchemaNameOrSearchPath(DatabricksConnection.java:37)
	at org.flywaydb.core.internal.database.base.Connection.<init>(Connection.java:53)
	at org.flywaydb.community.database.databricks.DatabricksConnection.<init>(DatabricksConnection.java:31)
	at org.flywaydb.community.database.databricks.DatabricksDatabase.doGetConnection(DatabricksDatabase.java:39)
	at org.flywaydb.community.database.databricks.DatabricksDatabase.doGetConnection(DatabricksDatabase.java:32)
	at org.flywaydb.core.internal.database.base.Database.getConnection(Database.java:104)
	at org.flywaydb.core.internal.database.base.Database.getMainConnection(Database.java:295)
	at org.flywaydb.core.internal.schemahistory.SchemaHistoryFactory.prepareSchemas(SchemaHistoryFactory.java:77)
	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:189)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:176)
	at org.flywaydb.commandline.Main.executeOperation(Main.java:298)
	at org.flywaydb.commandline.Main.executeFlyway(Main.java:204)
Caused by: com.databricks.client.support.exceptions.GeneralException: [Databricks][JDBCDriver](500051) ERROR processing query/statement. Error Code: 0, SQL state: null, Query: SELECT current_schema(), Error message from Server: Configuration key1 is not available..
	... 35 more
```

Please let me know if I can help with something else or if I am missing something.
Regards,

**Comment by JasonLuo-Redgate** [comment]
Hi @rafaelqntn-cfi ,

Thanks for the detailed feedback. I’d like to understand where exactly you used `key1` for replacement. 
If you remove `key1` from R__repeatable.sql, do you still encounter the same error?

**Comment by JasonLuo-Redgate** [comment]
Hi @rafaelqntn-cfi ,

Could you help try a  **Scenario 4**:

- Placeholders in the command
- No placeholders in SQL file

**Comment by rafaelqntn-cfi** [comment]
## Scenario 4
- Placeholders in the command
- No placeholders in SQL file

### Command:
```
flyway migrate -environment=dev -placeholders.key1=value -configFiles=.\sql\migrations\conf\flyway.toml -locations=filesystem:./sql/migrations -n -X
```

### Migration file:
R__repeatable.sql
```
select 'no placeholder';
```

### Output:
```
[...]
DEBUG: Using configuration:
[...]
flyway.placeholders -> {key1=value}
[...]
ERROR: Unexpected error
org.flywaydb.core.internal.exception.FlywaySqlException: Unable to determine the original schema for the connection
----------------------------------------------------------
SQL State  : HY000
Error Code : 500051
Message    : [Databricks][JDBCDriver](500051) ERROR processing query/statement. Error Code: 0, SQL state: null, Query: SELECT cur***, Error message from Server: Configuration key1 is not available..

	at org.flywaydb.core.internal.database.base.Connection.<init>(Connection.java:55)
	at org.flywaydb.community.database.databricks.DatabricksConnection.<init>(DatabricksConnection.java:31)
	at org.flywaydb.community.database.databricks.DatabricksDatabase.doGetConnection(DatabricksDatabase.java:39)
	at org.flywaydb.community.database.databricks.DatabricksDatabase.doGetConnection(DatabricksDatabase.java:32)
	at org.flywaydb.core.internal.database.base.Database.getConnection(Database.java:104)
	at org.flywaydb.core.internal.database.base.Database.getMainConnection(Database.java:295)
	at org.flywaydb.core.internal.schemahistory.SchemaHistoryFactory.prepareSchemas(SchemaHistoryFactory.java:77)
	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:189)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:176)
	at org.flywaydb.commandline.Main.executeOperation(Main.java:298)
	at org.flywaydb.commandline.Main.executeFlyway(Main.java:204)
	at org.flywaydb.commandline.Main.main(Main.java:127)
Caused by: java.sql.SQLException: [Databricks][JDBCDriver](500051) ERROR processing query/statement. Error Code: 0, SQL state: null, Query: SELECT cur***, Error message from Server: Configuration key1 is not available..
	at com.databricks.client.hivecommon.api.HS2Client.buildExceptionFromTStatusSqlState(Unknown Source)
	at com.databricks.client.hivecommon.api.HS2Client.pollForOperationCompletion(Unknown Source)
	at com.databricks.client.hivecommon.api.HS2Client.executeStatementInternal(Unknown Source)
	at com.databricks.client.hivecommon.api.HS2Client.executeStatement(Unknown Source)
	at com.databricks.client.hivecommon.dataengine.HiveJDBCNativeQueryExecutor.executeNonRowCountQueryHelper(Unknown Source)
	at com.databricks.client.hivecommon.dataengine.HiveJDBCNativeQueryExecutor.executeQuery(Unknown Source)
	at com.databricks.client.hivecommon.dataengine.HiveJDBCNativeQueryExecutor.<init>(Unknown Source)
	at com.databricks.client.hivecommon.dataengine.HiveJDBCDataEngine.prepare(Unknown Source)
	at com.databricks.client.jdbc.common.SPreparedStatement.<init>(Unknown Source)
	at com.databricks.client.jdbc.jdbc41.S41PreparedStatement.<init>(Unknown Source)
	at com.databricks.client.jdbc.jdbc42.S42PreparedStatement.<init>(Unknown Source)
	at com.databricks.client.hivecommon.jdbc42.Hive42PreparedStatement.<init>(Unknown Source)
	at com.databricks.client.spark.jdbc.SparkJDBCObjectFactory.createPreparedStatement(Unknown Source)
	at com.databricks.client.jdbc.common.JDBCObjectFactory.newPreparedStatement(Unknown Source)
	at com.databricks.client.jdbc.common.SConnection$5.create(Unknown Source)
	at com.databricks.client.jdbc.common.SConnection$5.create(Unknown Source)
	at com.databricks.client.jdbc.common.SConnection$StatementCreator.create(Unknown Source)
	at com.databricks.client.jdbc.common.SConnection.prepareStatement(Unknown Source)
	at com.databricks.client.jdbc.common.SConnection.prepareStatement(Unknown Source)
	at com.databricks.client.jdbc.common.SConnection.prepareStatement(Unknown Source)
	at org.flywaydb.core.internal.jdbc.JdbcTemplate.prepareStatement(JdbcTemplate.java:313)
	at org.flywaydb.core.internal.jdbc.JdbcTemplate.queryForString(JdbcTemplate.java:164)
	at org.flywaydb.community.database.databricks.DatabricksConnection.getCurrentSchemaNameOrSearchPath(DatabricksConnection.java:37)
	at org.flywaydb.core.internal.database.base.Connection.<init>(Connection.java:53)
	at org.flywaydb.community.database.databricks.DatabricksConnection.<init>(DatabricksConnection.java:31)
	at org.flywaydb.community.database.databricks.DatabricksDatabase.doGetConnection(DatabricksDatabase.java:39)
	at org.flywaydb.community.database.databricks.DatabricksDatabase.doGetConnection(DatabricksDatabase.java:32)
	at org.flywaydb.core.internal.database.base.Database.getConnection(Database.java:104)
	at org.flywaydb.core.internal.database.base.Database.getMainConnection(Database.java:295)
	at org.flywaydb.core.internal.schemahistory.SchemaHistoryFactory.prepareSchemas(SchemaHistoryFactory.java:77)
	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:189)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:176)
	at org.flywaydb.commandline.Main.executeOperation(Main.java:298)
	at org.flywaydb.commandline.Main.executeFlyway(Main.java:204)
Caused by: com.databricks.client.support.exceptions.GeneralException: [Databricks][JDBCDriver](500051) ERROR processing query/statement. Error Code: 0, SQL state: null, Query: SELECT cur***, Error message from Server: Configuration key1 is not available..
	... 34 more
```

### Result: `FAILED`.

**Comment by rafaelqntn-cfi** [comment]
@JasonLuo-Redgate, please check the comment above.
It's almost the same output as the **Scenario 2**, except for the slightly redacted query.
```
SELECT cur***, Error message from Server: Configuration key1 is not available.
```
It complains about the "missing configuration," although the Flyway debug message demonstrates that the placeholder has been correctly loaded `flyway.placeholders -> {key1=value}`

**Comment by JasonLuo-Redgate** [comment]
Hi @rafaelqntn-cfi ,

From **Scenario 4** we can see the most tricky part: the placeholder is only configured but never used anywhere.  

However, the JDBCDriver still complained about the error.

**Comment by rafaelqntn-cfi** [comment]
Yes, that's why I suspect that it's a JDBC issue.

I've seen similar error messages in discussion forums, and the problem goes around the "options" we can pass to the driver like this:
```
table = (spark.read
  .format("jdbc")
  .option("url", "<jdbc-url>")
  .option("dbtable", "<table-name>")
  .option("user", "<username>")
  .option("password", "<password>")
  .load()
)
```
When used this way, the options keys/values go to a "Configuration" object to change the connection parameters.
The Configuration object seems to expect the placeholder keys/values in there. As it does not find, it fails.

I could not inspect that part of the JDBC code, but if I appended `;key1=value1` to the `url` like below:

```
[flyway]
defaultSchema = "flyway_test"

[environments.dev]
url = "jdbc:databricks://[REDACTED];ConnCatalog=dev;httpPath=[REDACTED];UseNativeQuery=1;transportMode=http;ssl=1;EnableArrow=0;AuthMech=3;UID=token;PWD=[REDACTED];key1=value1"
```
With no placeholder configuration whatsoever, then it fails with the same error `Query: SELECT cur***, Error message from Server: Configuration key1 is not available.` See below:

```
ERROR: Unexpected error
org.flywaydb.core.internal.exception.FlywaySqlException: Unable to determine the original schema for the connection
----------------------------------------------------------
SQL State  : HY000
Error Code : 500051
Message    : [Databricks][JDBCDriver](500051) ERROR processing query/statement. Error Code: 0, SQL state: null, Query: SELECT cur***, Error message from Server: Configuration key1 is not available..

        at org.flywaydb.core.internal.database.base.Connection.<init>(Connection.java:55)
        at org.flywaydb.community.database.databricks.DatabricksConnection.<init>(DatabricksConnection.java:31)
        at org.flywaydb.community.database.databricks.DatabricksDatabase.doGetConnection(DatabricksDatabase.java:39)
        at org.flywaydb.community.database.databricks.DatabricksDatabase.doGetConnection(DatabricksDatabase.java:32)
        at org.flywaydb.core.internal.database.base.Database.getConnection(Database.java:104)
        at org.flywaydb.core.internal.database.base.Database.getMainConnection(Database.java:295)
        at org.flywaydb.core.internal.schemahistory.SchemaHistoryFactory.prepareSchemas(SchemaHistoryFactory.java:77)
        at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:189)
        at org.flywaydb.core.Flyway.migrate(Flyway.java:176)
        at org.flywaydb.commandline.Main.executeOperation(Main.java:298)
        at org.flywaydb.commandline.Main.executeFlyway(Main.java:204)
        at org.flywaydb.commandline.Main.main(Main.java:127)
Caused by: java.sql.SQLException: [Databricks][JDBCDriver](500051) ERROR processing query/statement. Error Code: 0, SQL state: null, Query: SELECT cur***, Error message from Server: Configuration key1 is not available..
        at com.databricks.client.hivecommon.api.HS2Client.buildExceptionFromTStatusSqlState(Unknown Source)
        at com.databricks.client.hivecommon.api.HS2Client.pollForOperationCompletion(Unknown Source)
        at com.databricks.client.hivecommon.api.HS2Client.executeStatementInternal(Unknown Source)
        at com.databricks.client.hivecommon.api.HS2Client.executeStatement(Unknown Source)
        at com.databricks.client.hivecommon.dataengine.HiveJDBCNativeQueryExecutor.executeNonRowCountQueryHelper(Unknown Source)
        at com.databricks.client.hivecommon.dataengine.HiveJDBCNativeQueryExecutor.executeQuery(Unknown Source)
        at com.databricks.client.hivecommon.dataengine.HiveJDBCNativeQueryExecutor.<init>(Unknown Source)
        at com.databricks.client.hivecommon.dataengine.HiveJDBCDataEngine.prepare(Unknown Source)
        at com.databricks.client.jdbc.common.SPreparedStatement.<init>(Unknown Source)
        at com.databricks.client.jdbc.jdbc41.S41PreparedStatement.<init>(Unknown Source)
        at com.databricks.client.jdbc.jdbc42.S42PreparedStatement.<init>(Unknown Source)
        at com.databricks.client.hivecommon.jdbc42.Hive42PreparedStatement.<init>(Unknown Source)
        at com.databricks.client.spark.jdbc.SparkJDBCObjectFactory.createPreparedStatement(Unknown Source)
        at com.databricks.client.jdbc.common.JDBCObjectFactory.newPreparedStatement(Unknown Source)
        at com.databricks.client.jdbc.common.SConnection$5.create(Unknown Source)
        at com.databricks.client.jdbc.common.SConnection$5.create(Unknown Source)
        at com.databricks.client.jdbc.common.SConnection$StatementCreator.create(Unknown Source)
        at com.databricks.client.jdbc.common.SConnection.prepareStatement(Unknown Source)
        at com.databricks.client.jdbc.common.SConnection.prepareStatement(Unknown Source)
        at com.databricks.client.jdbc.common.SConnection.prepareStatement(Unknown Source)
        at org.flywaydb.core.internal.jdbc.JdbcTemplate.prepareStatement(JdbcTemplate.java:313)
        at org.flywaydb.core.internal.jdbc.JdbcTemplate.queryForString(JdbcTemplate.java:164)
        at org.flywaydb.community.database.databricks.DatabricksConnection.getCurrentSchemaNameOrSearchPath(DatabricksConnection.java:37)
        at org.flywaydb.core.internal.database.base.Connection.<init>(Connection.java:53)
        at org.flywaydb.community.database.databricks.DatabricksConnection.<init>(DatabricksConnection.java:31)
        at org.flywaydb.community.database.databricks.DatabricksDatabase.doGetConnection(DatabricksDatabase.java:39)
        at org.flywaydb.community.database.databricks.DatabricksDatabase.doGetConnection(DatabricksDatabase.java:32)
        at org.flywaydb.core.internal.database.base.Database.getConnection(Database.java:104)
        at org.flywaydb.core.internal.database.base.Database.getMainConnection(Database.java:295)
        at org.flywaydb.core.internal.schemahistory.SchemaHistoryFactory.prepareSchemas(SchemaHistoryFactory.java:77)
        at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:189)
        at org.flywaydb.core.Flyway.migrate(Flyway.java:176)
        at org.flywaydb.commandline.Main.executeOperation(Main.java:298)
        at org.flywaydb.commandline.Main.executeFlyway(Main.java:204)
Caused by: com.databricks.client.support.exceptions.GeneralException: [Databricks][JDBCDriver](500051) ERROR processing query/statement. Error Code: 0, SQL state: null, Query: SELECT cur***, Error message from Server: Configuration key1 is not available..
        ... 34 more
```

**Comment by JasonLuo-Redgate** [comment]
Hi @rafaelqntn-cfi ,

At this point, it looks like this error is more about the Databricks JDBC driver than Flyway, so there’s not much Flyway can do to fix it.

**Comment by WilliamL-RG** [comment]
Hello, we have done some investigation into this issue and we have not been able to replicate this issue. Would you be able to try this docker image to see if you get the same results?
[Databricks.zip](https://github.com/user-attachments/files/17677934/Databricks.zip)

**Comment by rafaelqntn-cfi** [comment]
Test using the image `flyway/flyway:10.20.1-alpine` to match the version of the original description:

Basically same as **Scenario 4**

### Command:
```
docker run --rm ^
 -v [REDACTED]:/flyway/conf ^
 -v [REDACTED]:/flyway/sql ^
 flyway/flyway:10.20.1-alpine ^
 migrate ^
 -environment=dev ^
 -placeholders.key1=value ^
 -n ^
 -X
```
### Migration file:
R__repeatable.sql
```
select 'no placeholder';
```

### Output:
```
[...]
DEBUG: Loading config file: /flyway/conf/flyway.toml
[...]
DEBUG: flyway.environment -> dev
flyway.placeholders -> {key1=value}
[...]
Caused by: com.databricks.client.support.exceptions.GeneralException: [Databricks][JDBCDriver](500051) ERROR processing query/statement. Error Code: 0, SQL state: null, Query: SELECT current_schema(), Error message from Server: Configuration key1 is not available..
	... 35 more
```
### Result: `FAILED`.

Please, check the complete DEBUG output.
[docker_flyway_10.20.1-alpine.txt](https://github.com/user-attachments/files/17684706/docker_flyway_10.20.1-alpine.txt)

**Comment by WilliamL-RG** [comment]
Hello @rafaelqntn-cfi,
We have looked into this further and found a smilar issue at the `SELECT Current_schema()` query where it would not run. This was run using Databricks 9.1 with Spark 3.1, while our earlier tests were using Databricks 15.4 with Spark 3.5. 
Which version of Databricks are you using to run this?

**Comment by JasonLuo-Redgate** [comment]
Hi @rafaelqntn-cfi ,

Flyway recently released version `10.22.0`, which includes a bug fix that might address this issue. Could you have a try the new `10.22.0` release and see if it resolves the problem?

**Comment by rafaelqntn-cfi** [comment]
Oh! @JasonLuo-Redgate, that worked!

### Command:
```
docker run --rm ^
 -v [REDACTED]:/flyway/conf ^
 -v [REDACTED]:/flyway/sql ^
 flyway/flyway:10.22-alpine ^
 migrate ^
 -environment=dev ^
 -placeholders.key1=value ^
 -n ^
 -X
```
### Migration file:
R__repeatable.sql
```
select 'placeholder key1=${key1}' as placeholder_config;
```

### Output:
```
[...]
DEBUG: Parsing R__repeatable.sql ...
DEBUG: Found statement at line 1: select 'placehoder key1=value' as placeholder_config
DEBUG: Performing operation in non-transactional context.
DEBUG: Starting migration of schema `flyway_test` with repeatable migration "repeatable" ...
Migrating schema `flyway_test` with repeatable migration "repeatable"
DEBUG: Executing SQL: select 'placeholder key1=value' as placeholder_config
+-----------------------+
| placeholder_config    |
+-----------------------+
| placeholder key1=value |
+-----------------------+

DEBUG: Successfully completed migration of schema `flyway_test` with repeatable migration "repeatable"
DEBUG: Schema History table `flyway_test`.`flyway_schema_history` successfully updated to reflect changes
[...]
```
### Result: `SUCCESS`.

Thanks a lot for fixing that!

Regards,

**Comment by kamalendubiswas-db** [comment]
thank you @JasonLuo-Redgate @rafaelqntn-cfi this is really appreciated!
